#!/usr/bin/env bash
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/WANGkz96/AI-Video-Gen.git}"
REPO_REF="${REPO_REF:-master}"
WORK_ROOT="${WORK_ROOT:-/workspace}"
APP_DIR="${APP_DIR:-${WORK_ROOT}/AI-Video-Gen}"
PORT="${PORT:-8090}"
GENERATOR_BACKEND="comfyui-ltx25"
GENERATOR_API_URL="${GENERATOR_API_URL:-http://127.0.0.1:18188}"
AI_VIDEO_GEN_PROVISIONING_STATUS="${AI_VIDEO_GEN_PROVISIONING_STATUS:-${APP_DIR}/data/provisioning-status.json}"
AI_VIDEO_GEN_MODEL_DOWNLOAD_MAX_ATTEMPTS="${AI_VIDEO_GEN_MODEL_DOWNLOAD_MAX_ATTEMPTS:-60}"
AI_VIDEO_GEN_MODEL_DOWNLOAD_RETRY_DELAY="${AI_VIDEO_GEN_MODEL_DOWNLOAD_RETRY_DELAY:-20}"
AI_VIDEO_GEN_ENABLE_LTX="${AI_VIDEO_GEN_ENABLE_LTX:-1}"
AI_VIDEO_GEN_ENABLE_LONGCAT="${AI_VIDEO_GEN_ENABLE_LONGCAT:-0}"
CORS_ORIGINS="${CORS_ORIGINS:-http://127.0.0.1:${PORT},http://localhost:${PORT}}"

mkdir -p "${WORK_ROOT}"

if [ ! -d "${APP_DIR}/.git" ]; then
  git clone "${REPO_URL}" "${APP_DIR}"
fi

cd "${APP_DIR}"
git fetch --all --tags --prune
git checkout "${REPO_REF}"

if git show-ref --verify --quiet "refs/remotes/origin/${REPO_REF}"; then
  git pull --ff-only origin "${REPO_REF}"
fi

PORT="${PORT}" \
GENERATOR_BACKEND="${GENERATOR_BACKEND}" \
GENERATOR_API_URL="${GENERATOR_API_URL}" \
LTX25_MEGAPIXELS="${LTX25_MEGAPIXELS:-0.9}" \
AI_VIDEO_GEN_PROVISIONING_STATUS="${AI_VIDEO_GEN_PROVISIONING_STATUS}" \
AI_VIDEO_GEN_MODEL_DOWNLOAD_MAX_ATTEMPTS="${AI_VIDEO_GEN_MODEL_DOWNLOAD_MAX_ATTEMPTS}" \
AI_VIDEO_GEN_MODEL_DOWNLOAD_RETRY_DELAY="${AI_VIDEO_GEN_MODEL_DOWNLOAD_RETRY_DELAY}" \
AI_VIDEO_GEN_ENABLE_LTX="${AI_VIDEO_GEN_ENABLE_LTX}" \
AI_VIDEO_GEN_ENABLE_LONGCAT="${AI_VIDEO_GEN_ENABLE_LONGCAT}" \
CORS_ORIGINS="${CORS_ORIGINS}" \
bash ./scripts/deploy_vast.sh
