#!/usr/bin/env bash
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/WANGkz96/AI-Video-Gen.git}"
REPO_REF="${REPO_REF:-master}"
WORK_ROOT="${WORK_ROOT:-/workspace}"
APP_DIR="${APP_DIR:-${WORK_ROOT}/AI-Video-Gen}"
PORT="${PORT:-8090}"
MODELS="${MODELS:-}"
GENERATOR_BACKEND="${GENERATOR_BACKEND:-comfyui-ltx23}"
GENERATOR_API_URL="${GENERATOR_API_URL:-http://127.0.0.1:18188}"
AI_VIDEO_GEN_DOWNLOAD_COMFY_MODELS="${AI_VIDEO_GEN_DOWNLOAD_COMFY_MODELS:-1}"
AI_VIDEO_GEN_PROVISIONING_STATUS="${AI_VIDEO_GEN_PROVISIONING_STATUS:-${APP_DIR}/data/provisioning-status.json}"
AI_VIDEO_GEN_MODEL_DOWNLOAD_MAX_ATTEMPTS="${AI_VIDEO_GEN_MODEL_DOWNLOAD_MAX_ATTEMPTS:-60}"
AI_VIDEO_GEN_MODEL_DOWNLOAD_RETRY_DELAY="${AI_VIDEO_GEN_MODEL_DOWNLOAD_RETRY_DELAY:-20}"
AI_VIDEO_GEN_ENABLE_LTX="${AI_VIDEO_GEN_ENABLE_LTX:-1}"
AI_VIDEO_GEN_ENABLE_LONGCAT="${AI_VIDEO_GEN_ENABLE_LONGCAT:-0}"
CORS_ORIGINS="${CORS_ORIGINS:-http://127.0.0.1:${PORT},http://localhost:${PORT}}"

case "${GENERATOR_BACKEND}" in
  comfyui-ltx23)
    ;;
  ltx-2.3-distilled|ltx23-distilled|ltx-native|ltx-2.3|wan2.2-ti2v-5b)
    echo "Legacy GENERATOR_BACKEND='${GENERATOR_BACKEND}' detected; using comfyui-ltx23."
    GENERATOR_BACKEND="comfyui-ltx23"
    ;;
esac

if [ "${AI_VIDEO_GEN_FORCE_LTX23_DISTILLED:-0}" = "1" ]; then
  echo "Ignoring legacy AI_VIDEO_GEN_FORCE_LTX23_DISTILLED=1; generation is handled by ComfyUI."
  GENERATOR_BACKEND="comfyui-ltx23"
fi

GENERATOR_API_URL="${GENERATOR_API_URL:-http://127.0.0.1:18188}"
AI_VIDEO_GEN_DOWNLOAD_COMFY_MODELS="${AI_VIDEO_GEN_DOWNLOAD_COMFY_MODELS:-1}"

mkdir -p "${WORK_ROOT}"

if [ ! -d "${APP_DIR}/.git" ]; then
  git clone "${REPO_URL}" "${APP_DIR}"
fi

cd "${APP_DIR}"
git fetch --all --tags --prune
git checkout "${REPO_REF}"

if git show-ref --verify --quiet "refs/remotes/origin/${REPO_REF}"; then
  git pull --ff-only origin "${REPO_REF}"
fi

PORT="${PORT}" \
MODELS="${MODELS}" \
GENERATOR_BACKEND="${GENERATOR_BACKEND}" \
GENERATOR_API_URL="${GENERATOR_API_URL}" \
AI_VIDEO_GEN_DOWNLOAD_COMFY_MODELS="${AI_VIDEO_GEN_DOWNLOAD_COMFY_MODELS}" \
AI_VIDEO_GEN_PROVISIONING_STATUS="${AI_VIDEO_GEN_PROVISIONING_STATUS}" \
AI_VIDEO_GEN_MODEL_DOWNLOAD_MAX_ATTEMPTS="${AI_VIDEO_GEN_MODEL_DOWNLOAD_MAX_ATTEMPTS}" \
AI_VIDEO_GEN_MODEL_DOWNLOAD_RETRY_DELAY="${AI_VIDEO_GEN_MODEL_DOWNLOAD_RETRY_DELAY}" \
AI_VIDEO_GEN_ENABLE_LTX="${AI_VIDEO_GEN_ENABLE_LTX}" \
AI_VIDEO_GEN_ENABLE_LONGCAT="${AI_VIDEO_GEN_ENABLE_LONGCAT}" \
CORS_ORIGINS="${CORS_ORIGINS}" \
bash ./scripts/deploy_vast.sh
